[package]
name = "vial"
description = "a micro micro-framework"
version = "0.0.9-dev"
authors = ["chris west <c@xvxx.io>"]
documentation = "https://docs.rs/vial/"
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/xvxx/vial"
readme = "README.md"

[package.metadata.release]
dev-version-ext = "dev"

[[example]]
name = "horrorshow"
required-features = ["horror"]

[[example]]
name = "state"
required-features = ["state"]

[features]
horror = ['horrorshow']
state = []
default = []

[dependencies]
threadpool = "1.7.1"
libc-strftime = "0.2.0"
percent-encoding = "2.1.0"

horrorshow = { version = "0.8.3", optional = true }

