[package]
name = "vial"
description = "a micro micro-framework"
version = "0.1.5-dev"
authors = ["chris west <c@xvxx.io>"]
documentation = "https://docs.rs/vial/"
homepage = "https://vial.rs/"
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/xvxx/vial"
readme = "README.md"
exclude = [
    "examples/*",
    "tests/*",
    "docs/*",
]

[package.metadata.release]
consolidate-commits = true
dev-version-ext = "dev"
pre-release-replacements = [
  {file="CHANGELOG.md", search="## v\\d+\\.\\d+\\.\\d+-dev", replace="## vX.X.X-dev\n\n## v{{version}}"},
]

[[example]]
name = "horror"
path = "examples/horror.rs"
required-features = ["horror"]

[[example]]
name = "json"
path = "examples/json.rs"
required-features = ["json_serde"]

[[example]]
name = "state"
path = "examples/state.rs"
required-features = ["state"]

[[example]]
name = "filters"
path = "examples/filters.rs"
required-features = ["state"]

[features]
horror = ['horrorshow']
json_serde = ['serde', 'serde_json']
state = []
default = []

[dependencies]
threadpool = "1.7.1"
libc-strftime = "0.2.0"

horrorshow = { version = "0.8.3", optional = true }
serde = { version = "1", optional = true }
serde_json = { version = "1", optional = true }
