[package]
name = "vial"
description = "a micro micro-framework"
version = "0.0.2"
authors = ["chris west <c@xvxx.io>"]
documentation = "https://docs.rs/vial/"
edition = "2018"
license = "MIT"
repository = "https://github.com/xvxx/vial"
readme = "README.md"

[package.metadata.release]
dev-version-ext = "dev"

[features]
markdown = ['pulldown-cmark', 'autolink']
default = []

[dependencies]
httparse = "1.3.4"
threadpool = "1.7.1"
libc-strftime = "0.2.0"
percent-encoding = "2.1.0"

pulldown-cmark = { version = "0.7", default-features = false, optional = true }
autolink = { version = "0.3.0", optional = true }
